#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [[ "$(uname -s)" != "Linux" ]]; then
  cat >&2 <<'EOF'
sync-ubuntu-env-from-local.sh is for the Ubuntu host stack only.
EOF
  exit 1
fi

DOMAIN="${DOMAIN:-imapplepie20.tplinkdns.com}"
RUN_USER="${RUN_USER:-$(id -un)}"
ENV_DIR="${ENV_DIR:-/etc/my-forever-music}"
RESTART=false
DRY_RUN=false

API_LOCAL_ENV="$REPO_ROOT/services/api/.env.local"
AI_LOCAL_ENV="$REPO_ROOT/services/ai/.env.local"
WEB_LOCAL_ENV="$REPO_ROOT/apps/web/.env.local"

usage() {
  cat <<USAGE
Usage: ./infra/scripts/sync-ubuntu-env-from-local.sh [options]

Copy local non-committed env files into /etc/my-forever-music for the Ubuntu
systemd stack. Values are never printed.

Options:
  --domain DOMAIN     public domain. Default: ${DOMAIN}
  --user USER         systemd service user. Default: ${RUN_USER}
  --api-env FILE      source API env file. Default: services/api/.env.local
  --ai-env FILE       source AI env file. Default: services/ai/.env.local if present
  --web-env FILE      source Web env file. Default: apps/web/.env.local if present
  --restart           restart AI/API/Web after installing env files
  --dry-run           print target key names only; do not write /etc
  -h, --help          show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      DOMAIN="${2:?--domain requires a value}"
      shift 2
      ;;
    --user)
      RUN_USER="${2:?--user requires a value}"
      shift 2
      ;;
    --api-env)
      API_LOCAL_ENV="${2:?--api-env requires a value}"
      shift 2
      ;;
    --ai-env)
      AI_LOCAL_ENV="${2:?--ai-env requires a value}"
      shift 2
      ;;
    --web-env)
      WEB_LOCAL_ENV="${2:?--web-env requires a value}"
      shift 2
      ;;
    --restart)
      RESTART=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

log() {
  printf '[sync-ubuntu-env] %s\n' "$*"
}

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    printf 'Missing required file: %s\n' "$path" >&2
    exit 1
  fi
}

merge_env_files() {
  local output="$1"
  shift

  python3 - "$output" "$@" <<'PY'
from __future__ import annotations

import pathlib
import re
import sys

out = pathlib.Path(sys.argv[1])
paths = [pathlib.Path(p) for p in sys.argv[2:]]
items: dict[str, str] = {}
order: list[str] = []
pattern = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$")

for path in paths:
    try:
        content = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        continue
    except OSError:
        continue
    for raw in content.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = pattern.match(raw)
        if not match:
            continue
        key, value = match.group(1), match.group(2)
        if key not in items:
            order.append(key)
        items[key] = value

with out.open("w", encoding="utf-8") as fh:
    fh.write("# Generated by infra/scripts/sync-ubuntu-env-from-local.sh\n")
    fh.write("# Do not commit this file. Values are server-local secrets/config.\n")
    for key in order:
        fh.write(f"{key}={items[key]}\n")
PY
}

append_forced_api_defaults() {
  local file="$1"
  cat >>"$file" <<EOF

# Ubuntu runtime defaults
SPRING_PROFILES_ACTIVE=database
API_PORT=8081
DB_HOST=127.0.0.1
DB_PORT=5432
DB_NAME=my_forever_music
AI_SERVICE_BASE_URL=http://127.0.0.1:8000
SPOTIFY_REDIRECT_URI=https://${DOMAIN}/platforms/oauth/callback
TIDAL_REDIRECT_URI=https://${DOMAIN}/platforms/oauth/callback
EOF
}

append_forced_ai_defaults() {
  local file="$1"
  cat >>"$file" <<'EOF'

# Ubuntu runtime defaults
AI_ENV=ubuntu-dev
AI_ROOT_PATH=/ai
AI_HOST=0.0.0.0
AI_PORT=8000
AI_MODEL_ARTIFACT_DIR=/srv/my-forever-music/services/ai/models
EOF
}

append_forced_web_defaults() {
  local file="$1"
  cat >>"$file" <<EOF

# Ubuntu runtime defaults
WEB_HOST=0.0.0.0
WEB_PORT=5173
VITE_PUBLIC_HOST=${DOMAIN}
VITE_HMR_PROTOCOL=wss
VITE_HMR_CLIENT_PORT=443
EOF
}

print_keys() {
  local label="$1"
  local file="$2"
  printf '[%s]\n' "$label"
  sed -n 's/^\([A-Za-z_][A-Za-z0-9_]*\)=.*/\1/p' "$file" | sort -u
}

copy_existing_env() {
  local name="$1"
  local output="$2"
  local source="$ENV_DIR/$name.env"

  : >"$output"
  if [[ "$DRY_RUN" == true ]]; then
    return
  fi

  if sudo test -f "$source"; then
    sudo cp "$source" "$output"
    sudo chown "$(id -u):$(id -g)" "$output"
    chmod 0600 "$output"
  fi
}

install_env() {
  local name="$1"
  local tmp="$2"
  local dest="$ENV_DIR/$name.env"

  if [[ "$DRY_RUN" == true ]]; then
    print_keys "$dest" "$tmp"
    return
  fi

  sudo install -d -m 0750 "$ENV_DIR"
  if [[ -f "$dest" ]]; then
    sudo cp "$dest" "$dest.bak.$(date +%F-%H%M%S)"
  fi
  sudo install -m 0640 "$tmp" "$dest"
  log "installed $dest"
}

require_file "$API_LOCAL_ENV"

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

API_TMP="$TMP_DIR/api.env"
AI_TMP="$TMP_DIR/ai.env"
WEB_TMP="$TMP_DIR/web.env"
CURRENT_API_ENV="$TMP_DIR/current-api.env"
CURRENT_AI_ENV="$TMP_DIR/current-ai.env"
CURRENT_WEB_ENV="$TMP_DIR/current-web.env"

copy_existing_env api "$CURRENT_API_ENV"
copy_existing_env ai "$CURRENT_AI_ENV"
copy_existing_env web "$CURRENT_WEB_ENV"

merge_env_files \
  "$API_TMP" \
  "$REPO_ROOT/infra/systemd/env/api.env.example" \
  "$CURRENT_API_ENV" \
  "$API_LOCAL_ENV"
append_forced_api_defaults "$API_TMP"

merge_env_files \
  "$AI_TMP" \
  "$REPO_ROOT/infra/systemd/env/ai.env.example" \
  "$CURRENT_AI_ENV" \
  "$AI_LOCAL_ENV"
append_forced_ai_defaults "$AI_TMP"

merge_env_files \
  "$WEB_TMP" \
  "$REPO_ROOT/infra/systemd/env/web.env.example" \
  "$CURRENT_WEB_ENV" \
  "$WEB_LOCAL_ENV"
append_forced_web_defaults "$WEB_TMP"

install_env api "$API_TMP"
install_env ai "$AI_TMP"
install_env web "$WEB_TMP"

if [[ "$DRY_RUN" == true ]]; then
  exit 0
fi

if [[ "$RESTART" == true ]]; then
  log "restarting systemd services"
  sudo systemctl restart "my-forever-music-ai@${RUN_USER}.service"
  sudo systemctl restart "my-forever-music-api@${RUN_USER}.service"
  sudo systemctl restart "my-forever-music-web@${RUN_USER}.service"
fi

log "done"
